from typing import Generator, List, Optional, Union
from bs4 import BeautifulSoup, Tag

MAX_LEN: int

class HTMLFragmentationError(Exception): ...

def split_message(source: str, max_len: int = MAX_LEN) -> Generator[str, None, None]: ...
def get_parent_tags(element: Tag) -> List[Tag]: ...
def create_wrapper_start(tags: List[Tag]) -> str: ...
def create_wrapper_end(tags: List[Tag]) -> str: ...
def is_unsplittable(element: Tag) -> bool: ...
def process_element(element: Union[Tag, str], parent_tags: Optional[List[Tag]] = None) -> List[str]: ... 